package oop.view;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import oop.model.Bill;
import oop.model.Gender;
import oop.model.MealType;
import oop.service.OrderService;

/**
 *
 * @author Kanji Antony
 */
public class orderFrame extends javax.swing.JFrame {
    

    /**
     * Creates new form ticketFrame
     */
    public orderFrame() {
        initComponents();
        tb_load();
       data_load();
    }
    
    public void tb_load(){
  
          DefaultTableModel dt = (DefaultTableModel) booking_table.getModel();
          dt.setRowCount(0);
  
    } 

  public void data_load(){
  
  
        // this will load values to the ticket type JComboBox
  
          Vector v = new Vector();
                       
              v.add("MALE");
              v.add("FEMALE");
              v.add("OTHER");
              
              DefaultComboBoxModel com = new DefaultComboBoxModel(v);
              gender.setModel(com);
              
        // this will load values to the meal type JComboBox      
  
          Vector v_cabin = new Vector();
                       
              v_cabin.add("BREAKFAST");
              v_cabin.add("LUNCH");
              v_cabin.add("DINNER");
              v_cabin.add("DRINKS");
              v_cabin.add("DESSERT");
              
              DefaultComboBoxModel com_cabin = new DefaultComboBoxModel(v_cabin);
              meal_type.setModel(com_cabin);          
                          
      
      
  }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        meal_price = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        meal_type = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        user_email = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        user_phone = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        user_bank = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        visa_number = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cash_on_delivery = new javax.swing.JTextField();
        confirm_booking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        booking_table = new javax.swing.JTable();
        meal_name = new javax.swing.JTextField();
        user_address = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Meal Price");

        meal_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meal_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal_priceActionPerformed(evt);
            }
        });
        meal_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                meal_priceKeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Meal Name");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Meal Type");

        meal_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meal_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select " }));
        meal_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal_typeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Gender");

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select " }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("User name");

        user_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        user_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_nameKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Email");

        user_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_emailActionPerformed(evt);
            }
        });
        user_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_emailKeyReleased(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Phone number");

        user_phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_phoneActionPerformed(evt);
            }
        });
        user_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_phoneKeyReleased(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Address");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Bank name");

        user_bank.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_bankActionPerformed(evt);
            }
        });
        user_bank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_bankKeyReleased(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Visa Number");

        visa_number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        visa_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visa_numberActionPerformed(evt);
            }
        });
        visa_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                visa_numberKeyReleased(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Cash on delivery");

        cash_on_delivery.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cash_on_delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash_on_deliveryActionPerformed(evt);
            }
        });
        cash_on_delivery.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cash_on_deliveryKeyReleased(evt);
            }
        });

        confirm_booking.setText("Checkout");
        confirm_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_bookingActionPerformed(evt);
            }
        });

        booking_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Email", "Phone", "Address", "Meal name", "Meal type", "Meal price", "Bank name", "Visa number", "Cash on delivery", "Pay date"
            }
        ));
        booking_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booking_tableMouseClicked(evt);
            }
        });
        booking_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                booking_tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(booking_table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("YAMMANI FOOD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confirm_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(meal_price))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(meal_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(meal_name, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(user_name))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(user_email))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(user_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(10, 10, 10))
                                    .addComponent(jLabel26))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user_address, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(cash_on_delivery))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(visa_number))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(user_bank)))))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(jLabel1)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user_bank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(visa_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(cash_on_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(meal_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(meal_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(meal_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(user_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(user_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(user_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addComponent(confirm_booking)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meal_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal_priceActionPerformed

    private void meal_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meal_priceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_meal_priceKeyReleased

    private void meal_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal_typeActionPerformed

        

    }//GEN-LAST:event_meal_typeActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed

       

    }//GEN-LAST:event_genderActionPerformed

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void user_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_nameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameKeyReleased

    private void user_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_emailActionPerformed

    private void user_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_emailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_user_emailKeyReleased

    private void user_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_phoneActionPerformed

    private void user_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_phoneKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_user_phoneKeyReleased

    private void user_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_bankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_bankActionPerformed

    private void user_bankKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_bankKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_user_bankKeyReleased

    private void visa_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visa_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visa_numberActionPerformed

    private void visa_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_visa_numberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_visa_numberKeyReleased

    private void cash_on_deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash_on_deliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cash_on_deliveryActionPerformed

    private void cash_on_deliveryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cash_on_deliveryKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cash_on_deliveryKeyReleased

    private void confirm_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_bookingActionPerformed

        if(meal_price.getText().equals("") || meal_name.getText().equals("") ||
            user_name.getText().equals("") || user_email.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No field should be empty");
        } else {

            
            MealType mealType = MealType.valueOf(meal_type.getSelectedItem().toString());
            String mealName = meal_name.getText();
            double mealPrice = Double.parseDouble(meal_price.getText());

            String username = user_name.getText();
            String userEmail= user_email.getText();
            int userphone = Integer.parseInt(user_phone.getText());       
            String userAddress = user_address.getText();
            Gender userGender = Gender.valueOf(gender.getSelectedItem().toString());
            

            //we then get information input for the billing purpose and insert to the billing service
            String userBank = user_bank.getText();
            int userVisa = Integer.parseInt(visa_number.getText());
            double userCashOnDelivery = Double.parseDouble(cash_on_delivery.getText());
            

            OrderService orderService = new OrderService();
            Bill orderBill = orderService.orderMeal(mealName, mealType, mealPrice, username, userphone, userEmail, userGender, userAddress, userBank, userBank, userCashOnDelivery);
            
            //initialise the table to view the details fetched
            DefaultTableModel dt = (DefaultTableModel) booking_table.getModel();

            //this is a data structure used to insert data into the table meal_type       
            
            Vector v = new Vector();

            v.add(orderBill.getCustomer().getName());
            v.add(orderBill.getCustomer().getGender());
            v.add(orderBill.getCustomer().getEmail());
            v.add(orderBill.getCustomer().getPhoneNo());
            v.add(orderBill.getCustomer().getAddress());
           
            v.add(orderBill.getItemBought().getMeal().get(0).getMealName());
            v.add(orderBill.getItemBought().getMeal().get(0).getMealType());
            v.add(orderBill.getItemBought().getPrice());
            
            v.add(orderBill.getOnlinePayment().getBankName());
            v.add(orderBill.getOnlinePayment().getVisaNumber());
            v.add(orderBill.getCashOnDelivery().getAdditionalPayment());
            v.add(orderBill.getPaymentDate());

            dt.addRow(v);
            
            
            
        }

    }//GEN-LAST:event_confirm_bookingActionPerformed

    private void booking_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booking_tableMouseClicked

        int r = booking_table.getSelectedRow();

        String destination  = booking_table.getValueAt(r, 1).toString();

    }//GEN-LAST:event_booking_tableMouseClicked

    private void booking_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_booking_tableKeyPressed

    }//GEN-LAST:event_booking_tableKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable booking_table;
    private javax.swing.JTextField cash_on_delivery;
    private javax.swing.JButton confirm_booking;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField meal_name;
    private javax.swing.JTextField meal_price;
    private javax.swing.JComboBox<String> meal_type;
    private javax.swing.JTextField user_address;
    private javax.swing.JTextField user_bank;
    private javax.swing.JTextField user_email;
    private javax.swing.JTextField user_name;
    private javax.swing.JTextField user_phone;
    private javax.swing.JTextField visa_number;
    // End of variables declaration//GEN-END:variables
}
